### ISSUE TITLE
github-actions: support schedule cron

### ISSUE THREAD

**Issue by pjfanning** [typelevel/sbt-typelevel#299]
Github Actions yml supports setting a schedule param. It would be nice to have sbt-typelevel-github-actions support an sbt param that allows users to set this.

```
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: '33 9 * * 4'
```

Example: https://github.com/apache/commons-crypto/blob/master/.github/workflows/codeql-analysis.yml
