### ISSUE TITLE
Provide an option to exclude a certain version of Scala from running scalafix

### ISSUE THREAD

**Issue by iRevive** [typelevel/sbt-typelevel#306]
When `tlCiScalafixCheck := true` the following step is generated:
```yaml
- name: Check scalafix lints
  if: matrix.java == 'temurin@8'
  run: sbt 'project ${{ matrix.project }}' '++${{ matrix.scala }}' 'scalafixAll --check'
```

Unfortunately, some scalafix rules do not work with Scala 3. 

It would be nice to have an option to exclude a certain version of scala from running scalafix. For example:
```scala
tlCiScalafixExcludedScalaVersion := List("3.1.2")
```

Generated step:
```yaml
- name: Check scalafix lints
  if: matrix.java == 'temurin@8' && matrix.scala != '3.1.2'
  run: sbt 'project ${{ matrix.project }}' '++${{ matrix.scala }}' 'scalafixAll --check'
```
