### ISSUE TITLE
Chop down artifact list in generated ci.yml

### ISSUE THREAD

**Issue by jeffmay** [typelevel/sbt-typelevel#395]
It would make pull requests easier to read if the list of artifacts compressed by `tar` were chopped down. See [this example](https://github.com/rallyhealth/scalacheck-ops/pull/62/files#diff-b803fcb7f17ed9235f1e5cb1fcd2f5d3b2838429d4368ae4c57ce4436577f03fL42-R91) of a workflow that was converted to hand-written to auto-generated

**Comment by armanbilge** [comment]
Thanks for the issue, but some more context/details about what exactly the problem is would be very helpful :)

**Comment by jeffmay** [comment]
Before:
```yaml
      - name: Compress target directories
        if: github.event_name != 'pull_request' && (startsWith(github.ref, 'refs/tags/v'))
        run: tar cf targets.tar core/target/1-15-jvm-2.13 core/target/1-js-3 core/target/1-js-2.13 joda/target/1-13-jvm-2.12 core/target/1-js-2.12 core/target/1-13-jvm-2.12 core/target/1-15-jvm-2.12 core/target/1-15-js-2.12 joda/target/1-15-jvm-3 joda/target/1-15-jvm-2.13 core/target/1-15-js-2.13 core/target/1-jvm-2.12 joda/target/1-14-jvm-2.13 core/target/1-native-3 target core/target/1-15-jvm-3 core/target/1-15-js-3 joda/target/1-14-jvm-2.12 core/target/1-15-native-3 joda/target/1-jvm-2.13 joda/target/1-15-jvm-2.12 core/target/1-14-jvm-2.12 joda/target/1-jvm-2.12 core/target/1-14-jvm-2.13 core/target/1-jvm-2.13 core/target/1-jvm-3 joda/target/1-jvm-3 core/target/1-15-native-2.13 core/target/1-native-2.13 project/target
```

After:
```yaml
      - name: Compress target directories
        if: github.event_name != 'pull_request' && (startsWith(github.ref, 'refs/tags/v'))
        run: |
          tar cf targets.tar \
          core/target/1-13-jvm-2.12 \
          core/target/1-14-jvm-2.12 \
          core/target/1-14-jvm-2.13 \
          core/target/1-15-js-2.12 \
          core/target/1-15-js-2.13 \
          core/target/1-15-js-3 \
          core/target/1-15-jvm-2.12 \
          core/target/1-15-jvm-2.13 \
          core/target/1-15-jvm-3 \
          core/target/1-15-native-2.13 \
          core/target/1-15-native-3 \
          core/target/1-js-2.12 \
          core/target/1-js-2.13 \
          core/target/1-js-3 \
          core/target/1-jvm-2.12 \
          core/target/1-jvm-2.13 \
          core/target/1-jvm-3 \
          core/target/1-native-2.13 \
          core/target/1-native-3 \
          joda/target/1-13-jvm-2.12 \
          joda/target/1-14-jvm-2.12 \
          joda/target/1-14-jvm-2.13 \
          joda/target/1-15-jvm-2.12 \
          joda/target/1-15-jvm-2.13 \
          joda/target/1-15-jvm-3 \
          joda/target/1-jvm-2.12 \
          joda/target/1-jvm-2.13 \
          joda/target/1-jvm-3 \
          project/target \
          target
```
