### ISSUE TITLE
Dependency submission includes spurious dependencies

### ISSUE THREAD

**Issue by Daenyth** [typelevel/sbt-typelevel#597]
My dependency submission includes a bunch of stuff that isn't actually in the dependency list:

![image](https://github.com/typelevel/sbt-typelevel/assets/14644/45ae298a-5657-4a71-be66-0718ce590ef4)

Build definition: https://github.com/Daenyth/cats-effect-guava/blob/main/build.sbt

**Comment by rossabaker** [comment]
The plugin checks all configurations, and Scala 3's toolchain is full of vulnerabilities.  This is my default configuration, which thoroughly scans production (i.e., `Runtime`), but whistles past the CI graveyard:

```yaml
        uses: scalacenter/sbt-dependency-submission@v2
        with:
          modules-ignore: 
          configs-ignore: compile-time scala-doc-tool scala-tool test
```

These comments record some of what it addresses:

```scala
      // These have several derelict dependencies that light up our
      // dependabot and obscure real dangers:
      // - protobuf < 3.16.3
      // - jackson-databind >= 2.13.0, < 2.13.4.1
      // - jsoup < 1.15.3
      // - snake-yaml <= 1.33
      "scala-doc-tool",
      // - protobuf < 3.16.3
      "scala-tool",
      // Old scala-library_2.13 comes in via scala3-library_3 via
      // scalac-compat-0.1.0.  Compile-only dependencies are no more
      // dangerous than scala-tool dependencies: they are a threat
      // within CI, but caught in other configurations if they affect
      // production.
      "compile-time",
```

**Comment by Daenyth** [comment]
I'm not familiar with the tool - how do I add those settings?

Also should we consider a thing out of the box to fix this? It's very surprising, and if it affects every library that cross-compiles for scala3 then it's a big wart IMO

**Comment by armanbilge** [comment]
You don't have to add those, because sbt-typelevel already does. So something besides those is still slipping through.

**Comment by mzuehlke** [comment]
In your case `sbt-typelevel` created the following configuration:

```yml
      - name: Submit Dependencies
        uses: scalacenter/sbt-dependency-submission@v2
        with:
          modules-ignore: root rootJS docs rootJVM rootNative
          configs-ignore: test scala-tool scala-doc-tool
```
https://github.com/Daenyth/cats-effect-guava/blob/main/.github/workflows/ci.yml#L197-L201

**Comment by mzuehlke** [comment]
And these are the submitted dependencies: 
https://api.github.com/repos/Daenyth/cats-effect-guava/dependency-graph/snapshots/7564237

**Comment by mzuehlke** [comment]
It seems `sbt-typelevel` is using the `modules-ignore` not correct:

```yml
  modules-ignore:
    description: |
      A list of space-separated names of modules to ignore. The action will not resolve nor submit the dependencies of these modules.
      The name of a module contains the name of the project and its binary version.
      Example: `foo_2.13 bar_2.13`
    required: false
    default: ''
```

And we are not adding the **binary version**.
