### ISSUE TITLE
Separate `push` and `pull_request` triggers

### ISSUE THREAD

**Issue by hugo-vrijswijk** [typelevel/sbt-typelevel#807]
I want to define this trigger in my workflow:

```yaml
on:
  push:
    branches:
      - main
  pull_request:
    types: [synchronize, opened, reopened]
```

Which will run a build on my main branch, and for any pull request activity. Currently a lot of PR's will have the same job running twice (for `push` and `pull_request` activity). Is there a way to define this in the GHA plugin?
